import torch
import torch.nn as nn
import torch.nn.functional as F

from .aggregation import MobileV2Residual


class DualAttentionAggregation(nn.Module):
    """
    Cost aggregation with dual-view attention.

    The attention still multiplies the cost volume, but the attention map is
    generated by fusing left/right backbone features at each scale.
    """

    requires_right_features = True

    def __init__(self, in_channels, left_att, blocks, expanse_ratio, backbone_channels):
        super().__init__()

        self.left_att = left_att
        self.expanse_ratio = expanse_ratio

        conv0 = [MobileV2Residual(in_channels, in_channels, stride=1, expanse_ratio=self.expanse_ratio)
                 for _ in range(blocks[0])]
        self.conv0 = nn.Sequential(*conv0)

        self.conv1 = MobileV2Residual(in_channels, in_channels * 2, stride=2, expanse_ratio=self.expanse_ratio)
        conv2_add = [MobileV2Residual(in_channels * 2, in_channels * 2, stride=1, expanse_ratio=self.expanse_ratio)
                     for _ in range(blocks[1] - 1)]
        self.conv2 = nn.Sequential(*conv2_add)

        self.conv3 = MobileV2Residual(in_channels * 2, in_channels * 4, stride=2, expanse_ratio=self.expanse_ratio)
        conv4_add = [MobileV2Residual(in_channels * 4, in_channels * 4, stride=1, expanse_ratio=self.expanse_ratio)
                     for _ in range(blocks[2] - 1)]
        self.conv4 = nn.Sequential(*conv4_add)

        self.conv5 = nn.Sequential(
            nn.ConvTranspose2d(in_channels * 4, in_channels * 2, 3, padding=1, output_padding=1, stride=2, bias=False),
            nn.BatchNorm2d(in_channels * 2))

        self.conv6 = nn.Sequential(
            nn.ConvTranspose2d(in_channels * 2, in_channels, 3, padding=1, output_padding=1, stride=2, bias=False),
            nn.BatchNorm2d(in_channels))

        self.redir1 = MobileV2Residual(in_channels, in_channels, stride=1, expanse_ratio=self.expanse_ratio)
        self.redir2 = MobileV2Residual(in_channels * 2, in_channels * 2, stride=1, expanse_ratio=self.expanse_ratio)

        if self.left_att:
            self.att0 = DualAttentionModule(in_channels, backbone_channels[0])
            self.att2 = DualAttentionModule(in_channels * 2, backbone_channels[1])
            self.att4 = DualAttentionModule(in_channels * 4, backbone_channels[2])

    def forward(self, x, features_left, features_right):
        x = self.conv0(x)
        if self.left_att:
            x = self.att0(x, features_left[0], features_right[0])

        conv1 = self.conv1(x)
        conv2 = self.conv2(conv1)
        if self.left_att:
            conv2 = self.att2(conv2, features_left[1], features_right[1])

        conv3 = self.conv3(conv2)
        conv4 = self.conv4(conv3)
        if self.left_att:
            conv4 = self.att4(conv4, features_left[2], features_right[2])

        conv5 = F.relu(self.conv5(conv4) + self.redir2(conv2), inplace=True)
        conv6 = F.relu(self.conv6(conv5) + self.redir1(x), inplace=True)

        return [conv6]


class DualAttentionModule(nn.Module):
    def __init__(self, dim, img_feat_dim):
        super().__init__()
        # Fuse symmetric cues: concat + sum (consistency) + diff (occlusion/discordance).
        self.mix = nn.Conv2d(img_feat_dim * 4, dim, 1)

        self.conv0_1 = nn.Conv2d(dim, dim, (1, 7), padding=(0, 3), groups=dim)
        self.conv0_2 = nn.Conv2d(dim, dim, (7, 1), padding=(3, 0), groups=dim)

        self.conv1_1 = nn.Conv2d(dim, dim, (1, 11), padding=(0, 5), groups=dim)
        self.conv1_2 = nn.Conv2d(dim, dim, (11, 1), padding=(5, 0), groups=dim)

        self.conv2_1 = nn.Conv2d(dim, dim, (1, 21), padding=(0, 10), groups=dim)
        self.conv2_2 = nn.Conv2d(dim, dim, (21, 1), padding=(10, 0), groups=dim)

        self.conv3 = nn.Conv2d(dim, dim, 1)

    def forward(self, cost, x_left, x_right):
        sum_feats = x_left + x_right
        diff_feats = x_left - x_right
        attn = torch.cat([x_left, x_right, sum_feats, diff_feats], dim=1)
        attn = self.mix(attn)

        attn_0 = self.conv0_1(attn)
        attn_0 = self.conv0_2(attn_0)

        attn_1 = self.conv1_1(attn)
        attn_1 = self.conv1_2(attn_1)

        attn_2 = self.conv2_1(attn)
        attn_2 = self.conv2_2(attn_2)

        attn = attn + attn_0 + attn_1 + attn_2
        attn = self.conv3(attn)
        return attn * cost
